name: "ubuntu os matrix chain CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  

jobs:

# https://github.com/actions/virtual-environments
  # ubuntu-1604-job:
  #   name: "ubuntu-16.04"
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  

  ubuntu-1804-job:
    name: "ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  

  ubuntu-2004-job:
    name: "ubuntu-20.04"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 

# https://github.com/githubfoam/ubuntu_sandbox/runs/6704481408?check_suite_focus=true
# Package python-dev is not available, but is referred to by another package
  ubuntu-2204-job:
    name: "ubuntu-22.04"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status

  ubuntu-job:
    name: "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
   