name: "Ubuntu CI workflow"


on:
  push:
    branches: [ test ]


jobs:

  ubuntu-2004-job:
    name: "ubuntu-latest-20.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status      
    - name: "deploy cuckoo"
      run: sudo make deploy-cuckoo-2004   
      # Volatility 3     OK       
    - name: "deploy volatility 3"
      run: sudo make deploy-volatility-2004   
       


  ubuntu-1804-job:
    name: "ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
    - name: "deploy cuckoo"
      run: sudo make deploy-cuckoo-1804  
      # Volatility 3   OK    
    - name: "deploy volatility 3"
      run: sudo make deploy-volatility-1804   

  ubuntu-1604-job:
    name: "ubuntu-16.04"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "deploy cuckoo"
      run: sudo make deploy-cuckoo-1604                           
      # Volatility 3 
      # RuntimeError: Volatility framework requires python version 3.6.0 or greater
    # - name: "deploy volatility 3"
    #   run: sudo make deploy-volatility-1604 
                             

