name: "Ubuntu CI workflow"


on:
  push:
    branches: [ dev ]


jobs:

  ubuntu-2004-job:
    name: "ubuntu-latest-20.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch    
    - name: "deploy dnsutils (dig)"
      run: |
        sudo apt-get install -y dnsutils              
        dig geeksforgeeks.org #query A record      
      # Volatility 3     OK       
    - name: "deploy volatility 3"
      run: sudo make deploy-volatility-2004 
    - name: "deploy x8"
      run: sudo make deploy-x8    
    # - name: "deploy remnux"
    #   run: sudo make deploy-remnux-2004   
    # - name: "deploy remnux docker"
    #   run: sudo make deploy-remnux-docker-2004                     
    # - name: "deploy cuckoo"
    #   run: sudo make deploy-cuckoo-2004   
 #   - name: "deploy nxlog"
  #     run: sudo make deploy-nxlog    
    # - name: configure
    #   run: ./configure
    # - name: make
    #   run: make      
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck  
  #   - name: "deploy zeppelin"
  #     run: sudo make deploy-zeppelin        


  ubuntu-1804-job:
    name: "ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
      # Volatility 3   OK    
    - name: "deploy volatility 3"
      run: sudo make deploy-volatility-1804   
    # - name: "deploy remnux"
    #   run: sudo make deploy1-remnux-2004             
    # - name: "deploy cuckoo"
    #   run: sudo make deploy-cuckoo-1804   
 #   - name: "deploy nxlog"
 #     run: sudo make deploy-nxlog              
 #   - name: "build cuda"
 #     run: sudo make deploy-cuda   

  ubuntu-1604-job:
    name: "ubuntu-16.04"
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
      # Volatility 3 
      # RuntimeError: Volatility framework requires python version 3.6.0 or greater
    # - name: "deploy volatility 3"
    #   run: sudo make deploy-volatility-1604 
    # - name: "deploy remnux"
    #   run: sudo make deploy-remnux-2004               
    # - name: "deploy cuckoo"
    #   run: sudo make deploy-cuckoo-1604 
  #   - name: "deploy nxlog"
  #     run: sudo make deploy-nxlog                                

