name: "Ubuntu volatility CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month  

jobs:

  ubuntu-latest-job:
    name: "ubuntu-latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status        
      # Volatility 3     OK       
    - name: "deploy volatility 3"
      run: sudo make deploy-volatility-latest

  ubuntu-2204-job:
    name: "ubuntu-22.04"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status        
      # Volatility 3     OK       
    - name: "deploy volatility 3"
      run: sudo make deploy-volatility-2204

  ubuntu-2004-job:
    name: "ubuntud-20.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status       
      # Volatility 3     OK       
    - name: "deploy volatility 3"
      run: sudo make deploy-volatility-2004   
       


  ubuntu-1804-job:
    name: "ubuntu-18.04"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status 
      # Volatility 3   OK    
    - name: "deploy volatility 3"
      run: sudo make deploy-volatility-1804   

                         
                             

